packages:
  - '!integration-tests/worker/dummy-repo/**'
  - '!integration-tests/worker/tmp/**'
  - '!integration-tests/cli/tmp/**'
  - '!integration-tests/cli/repo/**'
  - '!packages/engine-multi/tmp/**'
  - packages/**
  - examples/**
  - integration-tests/**
  - '!**/test/**'

allowBuilds:
  '@swc/core': true
  esbuild: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@openfn/*'

overrides:
  path-to-regexp@8.3.0: ^8.4.0
