packages:
  - '!integration-tests/worker/dummy-repo/**'
  - '!integration-tests/worker/tmp/**'
  - '!integration-tests/cli/tmp/**'
  - '!integration-tests/cli/repo/**'
  - '!packages/engine-multi/tmp/**'
  - packages/**
  - examples/**
  - integration-tests/**
  - '!**/test/**'

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - oxc-resolver

overrides:
  path-to-regexp@8.3.0: ^8.4.0
