packages:
  - '!integration-tests/worker/dummy-repo/**'
  - '!integration-tests/worker/tmp/**'
  - '!integration-tests/cli/tmp/**'
  - '!integration-tests/cli/repo/**'
  - packages/**
  - examples/**
  - integration-tests/**
  - '!**/test/**'

minimumReleaseAge: 1440
