packages:
  # exclude the integration test repos
  - '!integration-tests/worker/dummy-repo/**'
  - '!integration-tests/worker/tmp/**'
  - '!integration-tests/cli/tmp/**'
  - '!integration-tests/cli/repo/**'

  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'examples/**'
  - 'integration-tests/**'

  # exclude packages that are inside test directories
  - '!**/test/**'
