packages:
  - '!integration-tests/worker/dummy-repo/**'
  - '!integration-tests/worker/tmp/**'
  - '!integration-tests/cli/tmp/**'
  - '!integration-tests/cli/repo/**'
  - packages/**
  - examples/**
  - integration-tests/**
  - '!**/test/**'

minimumReleaseAge: 4320

overrides:
  '@openfn/language-collections': link:../../../.local/share/pnpm/global/5/node_modules/@openfn/language-collections
