name: Publish to npm and dockerhub

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      ws_worker_tagged: ${{ steps.tags.outputs.ws_worker_tagged }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v6
        with:
          node-version: '24.14'
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm publish -r --report-summary --publish-branch main --access=public

      - run: git config user.name ${{ secrets.GH_USER }}
      - run: git config user.email ${{ secrets.GH_EMAIL }}

      - name: Push tags
        id: tags
        run: |
          pnpm changeset tag
          if git tag -l '@openfn/ws-worker@*' | grep -q .; then
            echo "ws_worker_tagged=true" >> $GITHUB_OUTPUT
          fi
          git push --tags

      - run: pnpm run generate-slack-report
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

  dockerize:
    needs: publish
    uses: ./.github/workflows/dockerize.yaml
    secrets: inherit
