name: Publish

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v6
        with:
          node-version: '22.12'
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm publish -r --report-summary --publish-branch main --access=public

      - run: git config user.name ${{ secrets.GH_USER }}
      - run: git config user.email ${{ secrets.GH_EMAIL }}

      - name: Push tags
        run: pnpm changeset tag && git push --tags

      - run: pnpm run generate-slack-report
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
